[package]
name = "guessing_game"
version = "0.1.0"
authors = ["ThatGuyJamal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5" # Upgrading to higher versions may break the code!
colored = "2.0.0"